/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication12;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Sava
 */
public class Program extends javax.swing.JFrame {

    /**
     * Creates new form Program
     */
    public Program() {
        initComponents();
    
    Show_Employee_In_JTable();
    }
    
    public Connection getConnection()
   {
       Connection con;

       try {
           con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/firma", "root", "marinko013");
          return con;
       } 
      catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }

    public ArrayList<Employee> getEmployeeList()
   {
       ArrayList<Employee> employeeList = new ArrayList<Employee>();
       Connection connection = getConnection();
       
       String query =  "SELECT * FROM  `employee`";
       Statement st;
       ResultSet rs;
       
       try {
           st = connection.createStatement();
           rs = st.executeQuery(query);

           Employee employee;

           while(rs.next())
           {
employee = new Employee(rs.getInt("Id"),rs.getString("FirstName"),rs.getString("LastName"),rs.getInt("Age"),rs.getString("Adress"),rs.getInt("Pid"));
               employeeList.add(employee);
           }

       } 
      catch (Exception e) {
           e.printStackTrace();
       }
       return employeeList;
   }
    
   public void Show_Employee_In_JTable()
{
    ArrayList<Employee> list = getEmployeeList();
    DefaultTableModel model = (DefaultTableModel) jTable_Display.getModel();
    Object[] row = new Object[6];
    for(int i=0; i<list.size(); i++){
        row[0] = list.get(i).getId();
        row[1] = list.get(i).getFirstName();
        row[2] = list.get(i).getLastName();
        row[3] = list.get(i).getAge();
        row[4] = list.get(i).getAdress();
        row[5] = list.get(i).getPid();
        
        model.addRow(row);
    }
}

public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               DefaultTableModel model = (DefaultTableModel)jTable_Display.getModel();
               model.setRowCount(0);
               Show_Employee_In_JTable();
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
   }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Id = new javax.swing.JLabel();
        jLabel_FirstName = new javax.swing.JLabel();
        jLabel_LastName = new javax.swing.JLabel();
        jLabel_Age = new javax.swing.JLabel();
        jLabel_Pid = new javax.swing.JLabel();
        jLabel_Adress = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jTextField_FirstName = new javax.swing.JTextField();
        jTextField_LastName = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Adress = new javax.swing.JTextField();
        jTextField_Pid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display = new javax.swing.JTable();
        jToggleButton_Insert = new javax.swing.JToggleButton();
        jToggleButton2_Update = new javax.swing.JToggleButton();
        jToggleButton3_Delete = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        jLabel_Id.setText("Id");

        jLabel_FirstName.setText("First Name");

        jLabel_LastName.setText("Last Name");

        jLabel_Age.setText("Age");

        jLabel_Pid.setText("Pid");

        jLabel_Adress.setText("Adress");

        jTextField_Id.setBackground(new java.awt.Color(239, 239, 227));
        jTextField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdActionPerformed(evt);
            }
        });

        jTextField_FirstName.setBackground(new java.awt.Color(239, 239, 227));
        jTextField_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FirstNameActionPerformed(evt);
            }
        });

        jTextField_LastName.setBackground(new java.awt.Color(239, 239, 227));
        jTextField_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LastNameActionPerformed(evt);
            }
        });

        jTextField_Age.setBackground(new java.awt.Color(239, 239, 227));

        jTextField_Adress.setBackground(new java.awt.Color(239, 239, 227));
        jTextField_Adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AdressActionPerformed(evt);
            }
        });

        jTextField_Pid.setBackground(new java.awt.Color(239, 239, 227));
        jTextField_Pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PidActionPerformed(evt);
            }
        });

        jTable_Display.setBackground(new java.awt.Color(238, 238, 228));
        jTable_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "FirstName", "LastName", "Age", "Adress", "Payments"
            }
        ));
        jTable_Display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display);

        jToggleButton_Insert.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButton_Insert.setText("Insert");
        jToggleButton_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_InsertActionPerformed(evt);
            }
        });

        jToggleButton2_Update.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButton2_Update.setText("Update");
        jToggleButton2_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2_UpdateActionPerformed(evt);
            }
        });

        jToggleButton3_Delete.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButton3_Delete.setText("Delete");
        jToggleButton3_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jToggleButton3_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jToggleButton2_Update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton_Insert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_FirstName)
                                .addComponent(jLabel_Id))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_FirstName)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_LastName)
                                .addComponent(jLabel_Age)
                                .addComponent(jLabel_Adress)
                                .addComponent(jLabel_Pid))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_LastName)
                                .addComponent(jTextField_Age)
                                .addComponent(jTextField_Adress)
                                .addComponent(jTextField_Pid)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Id)
                            .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_FirstName)
                            .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_LastName)
                            .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Age)
                            .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Adress)
                            .addComponent(jTextField_Adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Pid)
                            .addComponent(jTextField_Pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton_Insert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2_Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton3_Delete)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2_UpdateActionPerformed
        String query = "UPDATE `employee` SET `FirstName`='"+jTextField_FirstName.getText()+"',`LastName`='"+jTextField_LastName.getText()+"',`Age`='"+jTextField_Age.getText()+"',`Adress`='"+jTextField_Adress.getText()+"',`Pid`="+jTextField_Pid.getText()+" WHERE `id` = "+jTextField_Id.getText();
       executeSQlQuery(query, "Updated");
    }//GEN-LAST:event_jToggleButton2_UpdateActionPerformed

    private void jTextField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdActionPerformed

    private void jTextField_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FirstNameActionPerformed

    private void jTextField_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LastNameActionPerformed

    private void jTextField_AdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AdressActionPerformed

    private void jToggleButton3_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3_DeleteActionPerformed
      String query = "DELETE FROM `employee` WHERE id = "+jTextField_Id.getText();
         executeSQlQuery(query, "Deleted");
    }//GEN-LAST:event_jToggleButton3_DeleteActionPerformed

    private void jTable_DisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DisplayMouseClicked
        int i = jTable_Display.getSelectedRow();
        TableModel  model = jTable_Display.getModel();
        jTextField_Id.setText(model.getValueAt(i,0).toString());
        jTextField_FirstName.setText(model.getValueAt(i,1).toString());
        jTextField_LastName.setText(model.getValueAt(i,2).toString());
        jTextField_Age.setText(model.getValueAt(i,3).toString());
        jTextField_Adress.setText(model.getValueAt(i,4).toString());
        jTextField_Pid.setText(model.getValueAt(i,5).toString());
       
        
    }//GEN-LAST:event_jTable_DisplayMouseClicked

    private void jToggleButton_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_InsertActionPerformed
        String query = "INSERT INTO `employee`(`FirstName`, `LastName`, `Age`,`Adress`,`Pid`) VALUES ('"+jTextField_FirstName.getText()+"','"+jTextField_LastName.getText()+"',"+jTextField_Age.getText()+",'"+jTextField_Adress.getText()+"','"+jTextField_Pid.getText()+"')";
              executeSQlQuery(query, "Inserted");
    }//GEN-LAST:event_jToggleButton_InsertActionPerformed

    private void jTextField_PidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Adress;
    private javax.swing.JLabel jLabel_Age;
    private javax.swing.JLabel jLabel_FirstName;
    private javax.swing.JLabel jLabel_Id;
    private javax.swing.JLabel jLabel_LastName;
    private javax.swing.JLabel jLabel_Pid;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display;
    private javax.swing.JTextField jTextField_Adress;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_LastName;
    private javax.swing.JTextField jTextField_Pid;
    private javax.swing.JToggleButton jToggleButton2_Update;
    private javax.swing.JToggleButton jToggleButton3_Delete;
    private javax.swing.JToggleButton jToggleButton_Insert;
    // End of variables declaration//GEN-END:variables
}
